name: Code prettier and build Check

on:
  pull_request:
    branches: [main] 

jobs:
  code-check:
    name: Prettier + Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 
      - name: Install dependencies
        run: npm install

      - name: Check Prettier formatting
        run: npx prettier --check .

      - name: Build project
        run: npm run build

