name: Prettier Format Check

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: Check Prettier Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run Prettier check
        working-directory: frontend
        run: npx prettier --check .

